export const courseList = [
  { title: "HTML & CSS part 1", day: 1 },
  { title: " HTML & CSS part 2", day: 2 },
  { title: "Git & Github", day: 3 },
  { title: "JavaScript part 1", day: 4 },
  { title: "JavaScript part 2", day: 5 },
  { title: "JavaScript part 3 ", day: 6 },
  { title: "JavaScript part 4 ", day: 7 },
  { title: "JavaScript part 5", day: 8 },
  { title: "JavaScript part 6", day: 9 },
  { title: "Vinala JS ", day: 10 },
  { title: "React JS part 1", day: 11 },
  { title: "React JS part 2", day: 12 },
  { title: "React JS part 3", day: 13 },
  { title: "React JS part 4", day: 14 },
  { title: "React JS part 5", day: 15 },
  { title: "React JS part 6", day: 16 },
  { title: "React JS part 7", day: 17 },
  { title: "React JS part 8", day: 18 },
  { title: "Node JS part 1", day: 19 },
  { title: "Node JS part 2", day: 20 },
  { title: "Node JS & React JS", day: 21 },
  { title: "MERN Stack part 1", day: 22 },
  { title: "MERN Stack part 2", day: 23 },
  { title: "MERN Stack part 3", day: 24 },
  { title: "MERN Stack part 4", day: 25 },
  { title: "MERN Stack part 5", day: 26 },
  { title: "MERN Stack part 6", day: 27 },
  { title: "Scrum, SDLC", day: 28 },
  { title: "Start Group Project", day: 29 },
];
